# Numpy Practice Session

In [1]:
import numpy as np

In [6]:
# Creating 1-D array
arr1 = np.array([5,5,5,])
arr1

array([5, 5, 5])

In [7]:
# Checking type of the array
type(arr1)

numpy.ndarray

In [8]:
# Creating 2-D array
arr2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Creating 1-D array of ones
arr3 = np.ones(3)
arr3

array([1., 1., 1.])

In [11]:
# Creating 1-D array of zeroes
arr4 = np.zeros(4)
arr4

array([0., 0., 0., 0.])

In [36]:
# Checking Average of an array of int/flot
arr_new = np.array([2,4,6,8,10])
arr_new.mean()

6.0

In [20]:
# Creating 2-D array of empty/random values
arr5 = np.empty([3,2])
arr5

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
# Creating an array of desired range
arr6 = np.arange(5)
arr6

array([0, 1, 2, 3, 4])

In [23]:
# Creating an array of desired interval (start and stop)
arr7 = np.arange(5,10)
arr7

array([5, 6, 7, 8, 9])

In [24]:
# Creating an array of desried interval and steps (start, stop, step)
arr8 = np.arange(5,20,2)
arr8
np.arange

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
# Creating an array of desired interval with specific number of values
arr9 = np.linspace(2,10,num=5)
arr9

array([ 2.,  4.,  6.,  8., 10.])

In [32]:
# Specific data types in an array
arr10 = np.ones(5, dtype="float64")
print(arr10, arr10.dtype)

[1. 1. 1. 1. 1.] float64


In [33]:
# Creating a 2-D array
arr11 = np.arange(9).reshape(3,3)
arr11

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
# Creating a 3-D array
arr12 = np.arange(12).reshape(2,3,2)
arr12

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [35]:
# Creating a 4-D array
arr13 = np.arange(24).reshape(2,2,3,2)
arr13

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

## Array Functions

In [37]:
a = np.array([2,66,7.8,12,90,164,567,3,9])

In [38]:
a.sort()
a

array([  2. ,   3. ,   7.8,   9. ,  12. ,  66. ,  90. , 164. , 567. ])

In [55]:
b = np.random.randint(200,size=10)
b

array([107, 198,  38,  10, 110, 155, 193, 167, 130, 189])

In [56]:
c = np.random.randint(50,size=10)
c

array([ 3, 43, 15, 31, 17,  1,  3, 23, 25, 23])

In [60]:
d = np.concatenate((b,c))
d

array([107, 198,  38,  10, 110, 155, 193, 167, 130, 189,   3,  43,  15,
        31,  17,   1,   3,  23,  25,  23])

In [62]:
arr1 = np.array([[1,2,3,4,5],[5,4,3,2,1]])
arr2 = np.array([[1,2,3],[4,5,6]])

In [66]:
arr3 = np.concatenate((arr1,arr2), axis=1)
arr3

array([[1, 2, 3, 4, 5, 1, 2, 3],
       [5, 4, 3, 2, 1, 4, 5, 6]])

In [69]:
arr11 = np.arange(9).reshape(3,3)
arr11

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
arr12 = np.arange(12).reshape(2,3,2)
arr12

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [73]:
# Checking dimension(axis), size(number of elements) and shape(structure) of an array
print(arr11.ndim, arr11.size, arr11.shape)
print(arr12.ndim, arr12.size, arr12.shape)

2 9 (3, 3)
3 12 (2, 3, 2)


In [80]:
# Reshaping 
arr12_new = np.reshape(arr12, newshape=(3,4))
arr12_new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
# Dimension covnersion 1-D to 2-D
a = np.array([1,2,3,4])
b = a[np.newaxis, :]
c = a[:, np.newaxis]
print(b)
print(b.shape)
print(c)
print(c.shape)

[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [94]:
a[1:3]

array([2, 3])

In [97]:
a+6

array([ 7,  8,  9, 10])

In [98]:
a*2

array([2, 4, 6, 8])

In [99]:
a.sum()

10